apiVersion: v1
kind: ServiceAccount
metadata:
  name: sunshine-as
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sunshine-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: sunshine-as
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-sunshine
  namespace: kube-system
  labels:
    app: kube-sunshine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-sunshine
  template:
    metadata:
      labels:
        app: kube-sunshine
    spec:
      serviceAccountName: sunshine-as
      containers:
      - name: sunshine
        image: jcregistry/sunshine:v1.1
        resources:
          limits:
            memory: 50Mi
            cpu: 50m
          requests:
            memory: 50Mi
            cpu: 50m
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: kubernetes.default
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
        - name: POD_RESTART_NUMBER
          value: "50"
